const ColorActionTypes = {
  SWITCH_INPUT_COLOR: 'SWITCH_INPUT_COLOR',
  CHANGE_R_VALUE: 'CHANGE_R_VALUE',
  CHANGE_G_VALUE: 'CHANGE_G_VALUE',
  CHANGE_B_VALUE: 'CHANGE_B_VALUE',
  CHANGE_HEX_VALUE: 'CHANGE_HEX_VALUE'
};

export default ColorActionTypes;